/**
 * Validation rules for event definitions.
 *
 * Keys come from catalog paths in Chronicler 2.0, so there are no key/path consistency checks;
 * structural problems (bad names, duplicate keys, nested correlations) are reported by
 * `walkCatalog` as `invalid-catalog` errors while parsing.
 */

import { DEFAULT_REQUIRED_LEVELS } from '../../core/constants';
import { isReservedTopLevelField } from '../../core/reserved';
import type { ParsedEvent, ParsedEventGroup, ParsedEventTree, ValidationError } from '../types';

const VALID_LEVELS = new Set<string>(DEFAULT_REQUIRED_LEVELS);
const RESERVED_PREFIX = 'chronicler';

const makeError = (type: ValidationError['type'], message: string): ValidationError => ({
  type,
  message,
});

const hasReservedPrefix = (key: string): boolean =>
  key === RESERVED_PREFIX || key.startsWith(`${RESERVED_PREFIX}.`);

const reservedPrefixError = (what: string, key: string): ValidationError =>
  makeError(
    'reserved-prefix',
    `${what} key "${key}" uses reserved prefix "${RESERVED_PREFIX}.". This prefix is reserved for internal Chronicler system events.`,
  );

/**
 * Validate parsed event tree
 */
export function validateEventTree(tree: ParsedEventTree): ValidationError[] {
  const errors: ValidationError[] = [...tree.errors];

  // Lifecycle events are generated by Chronicler; their problems belong to the correlation.
  for (const event of tree.events) {
    if (!event.lifecycle) errors.push(...validateEvent(event));
  }

  const stack = [...tree.groups];
  while (stack.length > 0) {
    const group = stack.pop()!;
    if (group.kind === 'correlation') errors.push(...validateCorrelation(group));
    stack.push(...Object.values(group.groups));
  }

  return errors;
}

/**
 * Validate a single event definition
 */
function validateEvent(event: ParsedEvent): ValidationError[] {
  const errors: ValidationError[] = [];

  if (hasReservedPrefix(event.key)) {
    errors.push(reservedPrefixError('Event', event.key));
  }

  if (!VALID_LEVELS.has(event.level)) {
    errors.push(
      makeError(
        'invalid-level',
        `Invalid log level "${event.level}" in event "${event.key}". Valid levels: ${DEFAULT_REQUIRED_LEVELS.join(', ')}`,
      ),
    );
  }

  if (!event.doc) {
    errors.push(makeError('missing-doc', `Event "${event.key}" is missing a "doc" description`));
  }

  for (const fieldName of Object.keys(event.fields)) {
    if (isReservedTopLevelField(fieldName)) {
      errors.push(
        makeError(
          'reserved-field',
          `Field "${fieldName}" in event "${event.key}" is a reserved field name`,
        ),
      );
    }
  }

  return errors;
}

/**
 * Validate a correlation's own settings (its events are validated with the rest).
 */
function validateCorrelation(group: ParsedEventGroup): ValidationError[] {
  const errors: ValidationError[] = [];

  if (hasReservedPrefix(group.key)) {
    errors.push(reservedPrefixError('Correlation', group.key));
  }

  if (group.timeout !== undefined && !(group.timeout >= 0)) {
    errors.push(
      makeError(
        'invalid-timeout',
        `Correlation "${group.key}" has invalid timeout: ${group.timeout}. Must be non-negative.`,
      ),
    );
  }

  return errors;
}

/**
 * Format validation errors for display
 */
export function formatErrors(errors: ValidationError[]): string {
  if (errors.length === 0) {
    return 'No errors found.';
  }

  const lines = errors.map((error) => {
    return `  ${error.type}: ${error.message}`;
  });

  return `Found ${errors.length} error(s):\n${lines.join('\n')}`;
}
